import type { Metadata } from "next";
import { Aref_Ruqaa, Cairo } from "next/font/google";
import "@/styles/globals.css";

const cairo = Cairo({ subsets: ["latin"], display: "swap" });
const aref = Aref_Ruqaa({
  variable: "--aref",
  subsets: ["arabic"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-peacoat-800 ${aref.variable} ${cairo.className}`}>
        {children}
      </body>
    </html>
  );
}
